-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 16:44:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS 'mydb';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `airline_id` INT NOT NULL AUTO_INCREMENT,
  `total_capacity` INT NULL,
  `total_carrying_capacity` INT NULL,
  PRIMARY KEY (`airline_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airplane` (
  `airplane_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `carrying_capacity` INT NOT NULL,
  `flying_range` INT NOT NULL,
  `fuel_consumption` DOUBLE NULL,
  `Airline_airline_id` INT NOT NULL,
  PRIMARY KEY (`airplane_id`),
  INDEX `fk_Airplane_Airline_idx` (`Airline_airline_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airplane_Airline`
    FOREIGN KEY (`Airline_airline_id`)
    REFERENCES `mydb`.`Airline` (`airline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
